### ISSUE TITLE
Add license and update README

### ISSUE THREAD

**Issue by EmiliaJarochowska** [nialsiG/trident#5]
Hi, I am handling your preprint for PCI Paleo. 
As part of the recommendation process, I would like to give you feedback on the code that is the subject of the preprint.
May I suggest that you consider adding the following information to your repository:
1. A license for the software
2. Running instructions in the README
3. Link to the preprint
4. A citation file for the release, see e.g. https://citation-file-format.github.io/
5. Depending on the license, you may want to think about instructions for contributors. If you allow re-use of the code, you may want to clarify how you would like people to modify it or propose changes.

**Comment by nialsiG** [comment]
Hi,
Thank you for your suggestions! 
I just added the license, I will add the other elements as soon as possible.

**Comment by nialsiG** [comment]
Update of the Readme file
